#!/bin/bash

# InterviewAI — Project Setup Script
# Run from: ~/Documents/homespace/interviewai
# Usage: bash setup.sh

set -e

echo "🚀 Setting up InterviewAI project structure..."

# ── DIRECTORIES ──────────────────────────────────────────────────────────────
mkdir -p docs/specs
mkdir -p docs/rules
mkdir -p docs/prompts/v1
mkdir -p docs/skills
mkdir -p apps/web
mkdir -p apps/api
mkdir -p packages/shared

echo "✓ Directories created"

# ── .gitignore ────────────────────────────────────────────────────────────────
cat > .gitignore << 'EOF'
# Personal dev context — never commit
CLAUDE.local.md

# Dependencies
node_modules/
.pnpm-store/

# Build outputs
.next/
dist/
build/

# Environment files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
*.log
npm-debug.log*

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/

# Prisma
prisma/migrations/dev.db

# Test coverage
coverage/
EOF

echo "✓ .gitignore created"

# ── CLAUDE.md ─────────────────────────────────────────────────────────────────
cat > CLAUDE.md << 'EOF'
# InterviewAI — CLAUDE.md
> Read this at the start of every session. Keep it accurate and concise.

## What this project is
A full-stack AI-powered mock interview platform. Users paste a JD + Resume,
get a personalised Q&A bank generated by Claude, study it in flashcard mode,
take a proctored mock interview (camera + mic), and receive a scored debrief
with improvement coaching.

## Tech Stack
| Layer      | Choice                  | Why                                      |
|------------|-------------------------|------------------------------------------|
| Frontend   | Next.js 14 (App Router) | SSR + file-based routing, best DX        |
| Styling    | Tailwind + shadcn/ui    | Utility-first + accessible components   |
| State      | Zustand + React Query   | Minimal boilerplate                      |
| Auth       | NextAuth.js             | OAuth + session management               |
| Backend    | Express + TypeScript    | Simple, explicit, easy to test           |
| ORM        | Prisma                  | Type-safe DB access, great migrations    |
| Database   | PostgreSQL               | Relational + JSONB for AI outputs        |
| Queue      | BullMQ + Redis          | Async Claude scoring jobs                |
| AI         | Claude claude-sonnet-4-6       | Via SDK, prompts version-controlled      |
| Storage    | GCS                     | Interview recordings                     |
| Deploy     | Vercel + Cloud Run      | GCP-native, familiar                     |

## Repository Structure
```
apps/web/          Next.js frontend
apps/api/          Express backend
packages/shared/   Shared TypeScript types
docs/specs/        Feature specifications (read before implementing)
docs/rules/        Coding rules (always follow)
docs/prompts/      Versioned Claude API prompts
docs/skills/       Project-specific how-to guides
```

## Coding Conventions
- All API responses return `{ data, error }` shape. Never return raw objects.
- Errors: throw `new AppError(message, statusCode)`. Never throw raw strings.
- All DB queries go through `apps/api/src/lib/db.ts`. Never use Prisma client directly in routes.
- Services handle business logic. Routes only parse input, call service, return response.
- All Claude API calls go through `apps/api/src/lib/claude.ts`. Never call Anthropic SDK directly.
- Prompts loaded from `/docs/prompts/` by version key. Never hardcode prompts in code.
- All API inputs validated with Zod schemas before processing.
- TypeScript strict mode everywhere. No `any`.

## Auth Rules
- Access token: JWT, 15 min TTL, in Authorization header
- Refresh token: opaque UUID, 7 days, httpOnly cookie, rotated on every use
- Admin routes: check `req.user.role === 'ADMIN'` via `requireAdmin` middleware
- Never trust client-side role — always verify server-side

## Environment Variables
- Server-only vars: no prefix
- Client-accessible vars: `NEXT_PUBLIC_` prefix
- Never commit .env files. Use .env.example for documentation.

## Running Locally
```bash
# Install all
pnpm install

# Start DB and Redis
docker-compose up -d

# Run migrations
pnpm --filter api prisma migrate dev

# Start both apps
pnpm dev
```

## Current Phase
Phase 0 — Project scaffold. See docs/PLAN.md for full roadmap.

## NEVER DO
- Never call Claude API from the frontend directly
- Never put business logic in route handlers
- Never skip Zod validation on API inputs
- Never commit .env files or secrets
- Never use raw SQL — always use Prisma
- Never hardcode prompts in TypeScript — use /docs/prompts/
EOF

echo "✓ CLAUDE.md created"

# ── CLAUDE.local.md ───────────────────────────────────────────────────────────
cat > CLAUDE.local.md << 'EOF'
# CLAUDE.local.md
> GITIGNORED — never commit this file. Personal dev context only.

## Local Environment
- Postgres: postgresql://postgres:password@localhost:5432/interviewai_dev
- Redis: redis://localhost:6379
- API: http://localhost:4000
- Web: http://localhost:3000

## Where I Left Off
- Last session: Project setup and scaffolding
- Next task: Write pnpm workspace config and docker-compose.yml
- Blocker: None

## Local Test Accounts
- Admin: admin@test.com / password123
- User: deepak@test.com / password123

## Personal Notes
<!-- Add anything Claude should know about your local setup -->
EOF

echo "✓ CLAUDE.local.md created"

# ── docs/PLAN.md ──────────────────────────────────────────────────────────────
cat > docs/PLAN.md << 'EOF'
# InterviewAI — Product & Engineering Plan

## Vision
Full-cycle AI interview prep platform.
JD + Resume → Q&A Bank → Study Mode → Mock Interview → Scored Debrief → Coaching

## Build Phases

### Phase 0 — Scaffold (Week 1) ← CURRENT
- [ ] pnpm monorepo + docker-compose
- [ ] CLAUDE.md + all docs/ files
- [ ] Database schema: users, sessions
- [ ] Auth: register, login, refresh, logout
- [ ] NextAuth.js frontend + protected routes
- [ ] GitHub Actions CI
- [ ] Deploy skeleton

### Phase 1 — Core Product (Weeks 2–3)
- [ ] JD + Resume input UI
- [ ] Claude API: generate Q&A bank
- [ ] Study mode: flashcards + spaced repetition
- [ ] User dashboard

### Phase 2 — Mock Interview (Weeks 4–5)
- [ ] Camera + mic + recording
- [ ] Live speech-to-text transcription
- [ ] TTS question read-aloud
- [ ] Interviewer personas + follow-up generation

### Phase 3 — Scoring & Debrief (Week 6)
- [ ] BullMQ async scoring jobs
- [ ] Per-answer Claude scoring
- [ ] Filler word + length analysis
- [ ] PDF debrief export

### Phase 4 — Admin Panel (Week 7)
- [ ] RBAC middleware
- [ ] User management
- [ ] Session logs + transcript viewer
- [ ] Prompt management UI
- [ ] Feature flags
- [ ] Audit log

### Phase 5+ — Intelligence, Monetisation, Scale
- [ ] Spaced repetition improvements
- [ ] Company-specific mode
- [ ] Stripe integration
- [ ] Team/hiring mode

## Last Updated
Phase 0 planning complete. Starting scaffold next.
EOF

echo "✓ docs/PLAN.md created"

# ── docs/rules/api-design.md ─────────────────────────────────────────────────
cat > docs/rules/api-design.md << 'EOF'
# Rule: API Design

## Response Shape
All endpoints return exactly:
```typescript
{ data: T | null, error: string | null }
```
Never return a raw object. Never return just an array.

## HTTP Status Codes
- 200: success (GET, PUT)
- 201: created (POST)
- 400: validation error
- 401: not authenticated
- 403: not authorised
- 404: not found
- 429: rate limited
- 500: server error (never expose internals)

## Pagination
All list endpoints: `?page=1&limit=20`
Return: `{ data: { items, total, page, totalPages }, error }`

## Error Handling
Throw `AppError(message, statusCode)` in services.
Global error handler catches and formats.
Never return stack traces in production.

## Route Naming
- Plural nouns: /users, /banks, /sessions
- Nested for ownership: /users/:id/banks
- Verbs only for non-CRUD actions: /sessions/:id/score
- Admin routes always under /admin/

## Validation
Zod for all request body, params, query params.
Validate at route level before calling service.
Return 400 with field-level errors on failure.
EOF

echo "✓ docs/rules/api-design.md created"

# ── docs/rules/auth.md ────────────────────────────────────────────────────────
cat > docs/rules/auth.md << 'EOF'
# Rule: Authentication & Authorisation

## Token Strategy
- Access token: JWT, signed with ACCESS_TOKEN_SECRET, 15min TTL
- Refresh token: opaque UUID, 7 days, httpOnly + Secure cookie
- Rotation: old refresh token deleted on every use
- Theft detection: if revoked token reused → invalidate ALL user sessions

## Middleware
- `authenticate`: validates access token, attaches req.user = { id, email, role }
- `requireAdmin`: checks req.user.role === 'ADMIN', returns 403 if not
- Apply `authenticate` to all protected routes
- Apply `requireAdmin` to all /admin/ routes

## Passwords
- bcrypt with saltRounds = 12
- Never store or log plain text passwords
- Password reset: 10-minute signed token, single use

## Session Storage
- Refresh tokens stored in `sessions` table
- Fields: token_hash, user_id, expires_at, revoked_at
- On logout: set revoked_at = now()
- Cleanup job: delete expired sessions daily

## NEVER
- Never trust role from client request
- Never put sensitive data in JWT payload beyond id, email, role
- Never return refresh token in response body — cookie only
EOF

echo "✓ docs/rules/auth.md created"

# ── docs/rules/ai-calls.md ───────────────────────────────────────────────────
cat > docs/rules/ai-calls.md << 'EOF'
# Rule: AI / Claude API Calls

## How to Call Claude
Always use `apps/api/src/lib/claude.ts`.
Never import Anthropic SDK directly in routes or services.

```typescript
import { claude } from '../lib/claude'
const result = await claude.complete({
  promptKey: 'generate-question-bank',
  version: 'v1',
  vars: { jd, resume }
})
```

## Prompt Loading
- All prompts live in /docs/prompts/{version}/{key}.md
- Loaded at startup and cached in memory
- Use promptKey + version — never hardcode prompt text in TypeScript
- To update: create new version folder, update version reference in config

## Cost Controls
- Log every Claude call: prompt_key, model, input_tokens, output_tokens, user_id
- Soft limit: 50 Claude calls per user per day (via feature flag)
- Hard limit: reject at 100 calls/day with 429
- Always set appropriate max_tokens — don't use 4096 for a 200-token task

## Async Scoring
- Never run Claude scoring synchronously in the interview endpoint
- All scoring jobs go into BullMQ queue: `scoring-queue`
- Worker: apps/api/src/workers/scoring.worker.ts
- Frontend polls /api/sessions/:id/status for completion

## Error Handling
- Wrap all Claude calls in try/catch
- On API error: log full error, return 503 to client
- On timeout (>30s): cancel, return 504
- Never expose raw Claude error messages to clients

## Output Validation
- All Claude JSON outputs validated with Zod before use
- If validation fails: log raw output, retry once with stricter prompt
- If retry fails: return 422 with "AI output could not be parsed"
EOF

echo "✓ docs/rules/ai-calls.md created"

# ── docs/rules/database.md ───────────────────────────────────────────────────
cat > docs/rules/database.md << 'EOF'
# Rule: Database

## Access Pattern
All DB queries go through `apps/api/src/lib/db.ts`.
Never import PrismaClient directly in routes or services.
Never write raw SQL — always use Prisma query methods.

## Migrations
- Never edit existing migration files
- Every schema change = new migration: `pnpm --filter api prisma migrate dev --name describe_change`
- Migration names: snake_case, descriptive (add_sessions_table, add_role_to_users)
- Always run migrations before deploying

## JSONB Usage
Use JSONB columns for: AI-generated outputs, flexible config, arrays of objects.
Always define a TypeScript type for JSONB contents.
Always validate JSONB contents with Zod when reading from DB.

## Indexes
Add indexes for: foreign keys, columns used in WHERE clauses, columns used in ORDER BY.
Document why each index exists in a comment above it in schema.prisma.

## Soft Deletes
Use `deleted_at` timestamp for user-facing data (banks, sessions).
Hard delete only for: sessions (auth tokens), audit logs (append-only).

## Naming
- Tables: snake_case plural (users, question_banks, mock_interviews)
- Columns: snake_case (created_at, user_id, token_hash)
- Foreign keys: {table_singular}_id (user_id, bank_id, session_id)
EOF

echo "✓ docs/rules/database.md created"

# ── docs/rules/testing.md ────────────────────────────────────────────────────
cat > docs/rules/testing.md << 'EOF'
# Rule: Testing

## What to Test
- All service layer functions (unit tests)
- All API endpoints (integration tests)
- Auth flows end-to-end
- Claude output parsing and validation logic

## What NOT to Test
- Prisma internals
- Third-party library internals
- Pure UI rendering (leave for E2E later)

## File Naming
- Unit: `{filename}.test.ts` next to the file being tested
- Integration: `apps/api/src/__tests__/{feature}.integration.test.ts`

## Mocking
- Mock Prisma using `jest-mock-extended`
- Mock Claude API calls — never hit real API in tests
- Mock BullMQ workers — test job logic separately from queue

## Coverage
- Services: aim for 80%+ coverage
- Routes: cover happy path + main error cases
- Auth: cover all token scenarios (expired, revoked, missing)

## Running Tests
```bash
pnpm --filter api test           # unit tests
pnpm --filter api test:int       # integration tests
pnpm test                        # all tests
```
EOF

echo "✓ docs/rules/testing.md created"

# ── docs/specs/auth.spec.md ───────────────────────────────────────────────────
cat > docs/specs/auth.spec.md << 'EOF'
# Spec: Authentication

## What it does
Users can register, log in, refresh their session, and log out.
Admins are identified by role and get access to /admin/ routes.

## Endpoints

### POST /api/auth/register
Request: { email, password, name }
Response 201: { data: { user: { id, email, name, role } }, error: null }
Response 400: validation error (email format, password min 8 chars)
Response 409: email already exists

### POST /api/auth/login
Request: { email, password }
Response 200: { data: { user, accessToken }, error: null }
Sets httpOnly cookie: refreshToken
Response 401: invalid credentials

### POST /api/auth/refresh
Reads refreshToken from cookie
Response 200: { data: { accessToken }, error: null }
Sets new refreshToken cookie, invalidates old one
Response 401: missing, expired, or revoked token

### POST /api/auth/logout
Reads refreshToken from cookie, revokes it
Clears cookie
Response 200: { data: { message: 'Logged out' }, error: null }

### GET /api/auth/me
Requires: authenticate middleware
Response 200: { data: { user: { id, email, name, role } }, error: null }

## Data Model Changes
- users table: id, email, password_hash, name, role (USER|ADMIN), created_at, suspended_at
- sessions table: id, user_id, token_hash, expires_at, revoked_at, created_at

## Acceptance Criteria
- [ ] User can register with email + password
- [ ] User can log in and receive access token + refresh cookie
- [ ] Access token expires after 15 minutes
- [ ] Refresh token rotates on every use
- [ ] Reusing a revoked refresh token invalidates all user sessions
- [ ] Logged out user cannot refresh or access protected routes
- [ ] Admin role blocks access to USER-only routes (403)

## Edge Cases
- Register with existing email → 409
- Login with wrong password → 401 (same message as wrong email, no enumeration)
- Refresh with expired token → 401
- Refresh with revoked token → 401 + revoke all user sessions
- Suspended user tries to login → 403

## Do NOT Change
- Do not add social login here — that comes in a separate task
- Do not add password reset here — separate spec
EOF

echo "✓ docs/specs/auth.spec.md created"

# ── docs/specs/study-mode.spec.md ────────────────────────────────────────────
cat > docs/specs/study-mode.spec.md << 'EOF'
# Spec: Study Mode

## What it does
Users study their generated Q&A bank using flashcards with spaced repetition.
Cards surface based on confidence ratings using the SM-2 algorithm.

## Key Features
- Flashcard flip: question front, answer back
- Confidence rating per card: Got it / Shaky / Need review
- SM-2 spaced repetition: weak cards surface more often
- Topic cluster progress rings
- "Ready to test" signal when all cards seen and < 3 marked weak
- AI hint: show partial answer without revealing full answer

## Endpoints

### GET /api/banks/:id/study
Returns next card due for review based on SM-2 schedule
Response: { data: { question, questionId, dueCount, totalCount }, error: null }

### POST /api/banks/:id/study/:questionId/rate
Request: { confidence: 'got_it' | 'shaky' | 'need_review' }
Updates SM-2 next_due_at for this card
Response: { data: { nextDue, nextCard }, error: null }

### GET /api/banks/:id/progress
Response: { data: { topics: [{ name, total, seen, confident }], readyToTest: bool } }

## Acceptance Criteria
- [ ] Cards with 'need_review' surface again within same session
- [ ] Cards with 'got_it' are not shown again for 24+ hours
- [ ] Topic progress updates in real time as cards are rated
- [ ] "Ready to test" only shows when genuinely ready
EOF

echo "✓ docs/specs/study-mode.spec.md created"

# ── docs/specs/mock-interview.spec.md ────────────────────────────────────────
cat > docs/specs/mock-interview.spec.md << 'EOF'
# Spec: Mock Interview

## What it does
User takes a timed mock interview with camera + mic.
Questions are read aloud. Answers are transcribed live.
Full session is recorded and saved.

## Flow
1. Setup screen: camera preview, mic test, persona selection, timer config
2. Intro: interviewer persona introduces themselves (TTS)
3. For each question:
   a. Question displayed + read aloud via TTS
   b. Timer starts
   c. User answers — live transcription shown
   d. Timer ends or user clicks "Next"
   e. AI generates a follow-up question based on answer (optional)
4. Session ends: recording uploaded, scoring job queued

## Endpoints

### POST /api/interviews
Request: { bankId, persona, timerSeconds }
Response 201: { data: { interviewId, questions }, error: null }

### POST /api/interviews/:id/answer
Request: { questionId, transcript }
Response 200: { data: { followUp, nextQuestionId }, error: null }

### POST /api/interviews/:id/complete
Request: { recordingUrl }
Queues scoring job
Response 200: { data: { interviewId, status: 'scoring' }, error: null }

### GET /api/interviews/:id/status
Response: { data: { status: 'scoring' | 'complete' | 'failed' }, error: null }

## Acceptance Criteria
- [ ] Camera and mic permissions handled gracefully (denied state shown)
- [ ] TTS reads each question before timer starts
- [ ] Live transcript updates as user speaks
- [ ] Recording saved to GCS on session complete
- [ ] Scoring job queued immediately after complete
- [ ] User redirected to debrief once scoring is done
EOF

echo "✓ docs/specs/mock-interview.spec.md created"

# ── docs/specs/scoring.spec.md ───────────────────────────────────────────────
cat > docs/specs/scoring.spec.md << 'EOF'
# Spec: Scoring & Debrief

## What it does
After a mock interview, each answer is scored by Claude against the ideal answer.
User sees a full debrief: per-answer scores, filler words, ideal answer, topic breakdown.

## Scoring Dimensions (per answer, 0-25 each = 100 total)
- Technical accuracy: Is the answer factually correct?
- Completeness: Did it cover the key points?
- Clarity: Was it clearly explained?
- Examples: Did the candidate use concrete examples?

## Filler Word Detection
Count occurrences of: "umm", "uhh", "like", "you know", "basically", "literally"
Flag if total fillers > 10% of word count

## Answer Length Classification
- Too short: < 50 words
- Optimal: 50–250 words
- Rambling: > 250 words

## Endpoints

### GET /api/interviews/:id/debrief
Response: {
  data: {
    overallScore,
    topicBreakdown: [{ topic, score, questionCount }],
    answers: [{
      questionId, question, transcript, score,
      dimensions: { accuracy, completeness, clarity, examples },
      fillerCount, wordCount, lengthClassification,
      idealAnswer, improvement
    }]
  }
}

## Acceptance Criteria
- [ ] Scoring runs async via BullMQ — never blocks the interview endpoint
- [ ] Each answer scored independently
- [ ] Filler words counted from raw transcript
- [ ] Ideal answer shown alongside user's transcript
- [ ] "Improved answer" generated by Claude
- [ ] PDF export of full debrief available
EOF

echo "✓ docs/specs/scoring.spec.md created"

# ── docs/specs/admin-panel.spec.md ───────────────────────────────────────────
cat > docs/specs/admin-panel.spec.md << 'EOF'
# Spec: Admin Panel

## What it does
Admins can view and manage all users, sessions, Q&A banks, prompts, and feature flags.
All admin actions are logged in the audit trail.

## Roles
- USER: own data only
- ADMIN: read all data, suspend users, update prompts + flags
- SUPER_ADMIN: all ADMIN permissions + manage other admins

## Key Pages
- /admin — dashboard: user count, mocks taken, avg score, API cost
- /admin/users — paginated user table with search + suspend
- /admin/users/[id] — user detail: activity, sessions, banks
- /admin/sessions — all mock sessions with filters
- /admin/sessions/[id] — full transcript + per-answer scores + recording
- /admin/prompts — prompt registry: view, edit, version history
- /admin/flags — feature flag toggles with rollout %
- /admin/audit — full audit log with filters

## Security Rules
- All /admin/ routes require requireAdmin middleware
- Every admin action writes to audit_logs
- Suspended users cannot log in
- Prompt updates create a new version — never overwrite

## Acceptance Criteria
- [ ] Non-admin user hitting /admin gets 403
- [ ] Admin can suspend/unsuspend a user
- [ ] Admin can view any session transcript
- [ ] Admin can update a prompt and see version history
- [ ] Every admin action appears in audit log within 1 second
EOF

echo "✓ docs/specs/admin-panel.spec.md created"

# ── docs/prompts/v1/generate-question-bank.md ────────────────────────────────
cat > docs/prompts/v1/generate-question-bank.md << 'EOF'
# Prompt: generate-question-bank
Version: v1
Model: claude-sonnet-4-6
Max tokens: 4096

## Purpose
Generate a personalised Q&A bank from a job description and/or resume.

## System Prompt
You are an expert technical interviewer. Given a job description and/or resume,
generate a comprehensive, personalised Q&A bank for interview preparation.

Rules:
- Generate exactly 20 questions
- Mix difficulty: 8 core, 8 deep-dive, 4 trap/edge-case questions
- Questions must be specific to the JD and candidate background
- Each answer should be 150-300 words
- Return ONLY valid JSON — no markdown, no explanation

## User Prompt Template
Job Description:
{{jd}}

Resume:
{{resume}}

Generate a Q&A bank as JSON with this exact shape:
{
  "topics": ["topic1", "topic2"],
  "questions": [
    {
      "id": "q1",
      "topic": "topic name",
      "difficulty": "core | deep | trap",
      "question": "...",
      "idealAnswer": "...",
      "whyItMatters": "one sentence on why this is asked for this role",
      "tags": ["tag1", "tag2"]
    }
  ]
}

## Output Schema (Zod)
z.object({
  topics: z.array(z.string()),
  questions: z.array(z.object({
    id: z.string(),
    topic: z.string(),
    difficulty: z.enum(['core', 'deep', 'trap']),
    question: z.string(),
    idealAnswer: z.string(),
    whyItMatters: z.string(),
    tags: z.array(z.string())
  }))
})
EOF

echo "✓ docs/prompts/v1/generate-question-bank.md created"

# ── docs/prompts/v1/score-answer.md ──────────────────────────────────────────
cat > docs/prompts/v1/score-answer.md << 'EOF'
# Prompt: score-answer
Version: v1
Model: claude-sonnet-4-6
Max tokens: 1024

## Purpose
Score a candidate's spoken answer against the ideal answer across 4 dimensions.

## System Prompt
You are a strict but fair technical interview evaluator.
Score the candidate's answer honestly. Do not inflate scores.
Return ONLY valid JSON — no markdown, no explanation.

## User Prompt Template
Question: {{question}}

Ideal Answer: {{idealAnswer}}

Candidate's Answer (transcribed from speech): {{transcript}}

Score this answer out of 25 for each dimension:
- accuracy: Is it technically correct?
- completeness: Did it cover the key points from the ideal answer?
- clarity: Was it clearly and logically explained?
- examples: Did the candidate use concrete, relevant examples?

Also provide:
- feedback: 2-3 sentences on what was good and what was missing
- improvement: Rewrite the candidate's answer as an ideal response

Return JSON:
{
  "scores": { "accuracy": 0-25, "completeness": 0-25, "clarity": 0-25, "examples": 0-25 },
  "total": 0-100,
  "feedback": "...",
  "improvement": "..."
}

## Output Schema (Zod)
z.object({
  scores: z.object({
    accuracy: z.number().min(0).max(25),
    completeness: z.number().min(0).max(25),
    clarity: z.number().min(0).max(25),
    examples: z.number().min(0).max(25),
  }),
  total: z.number().min(0).max(100),
  feedback: z.string(),
  improvement: z.string()
})
EOF

echo "✓ docs/prompts/v1/score-answer.md created"

# ── docs/prompts/v1/generate-followup.md ─────────────────────────────────────
cat > docs/prompts/v1/generate-followup.md << 'EOF'
# Prompt: generate-followup
Version: v1
Model: claude-sonnet-4-6
Max tokens: 256

## Purpose
Generate a natural interviewer follow-up question based on the candidate's answer.

## System Prompt
You are a senior technical interviewer conducting a real interview.
Based on what the candidate just said, ask ONE sharp follow-up question.
Probe for depth, specifics, or a gap you noticed in their answer.
Return ONLY the follow-up question as plain text — no explanation.

## User Prompt Template
Original Question: {{question}}
Candidate's Answer: {{transcript}}

Ask a follow-up question that probes deeper into their answer.
EOF

echo "✓ docs/prompts/v1/generate-followup.md created"

# ── docs/prompts/v1/extract-jd-signals.md ────────────────────────────────────
cat > docs/prompts/v1/extract-jd-signals.md << 'EOF'
# Prompt: extract-jd-signals
Version: v1
Model: claude-sonnet-4-6
Max tokens: 512

## Purpose
Extract structured signals from a job description to personalise the Q&A bank.

## System Prompt
Extract key signals from this job description.
Return ONLY valid JSON — no markdown, no explanation.

## User Prompt Template
Job Description:
{{jd}}

Extract:
{
  "role": "job title",
  "seniority": "junior | mid | senior | staff | principal",
  "techStack": ["tech1", "tech2"],
  "keyTopics": ["topic1", "topic2"],
  "companySignals": "1-2 sentences about company culture/style from the JD",
  "interviewStyle": "likely interview style based on JD language"
}
EOF

echo "✓ docs/prompts/v1/extract-jd-signals.md created"

# ── docs/skills/api-route.md ──────────────────────────────────────────────────
cat > docs/skills/api-route.md << 'EOF'
# Skill: How to Add a New API Route

## Step 1 — Create the route file
Location: `apps/api/src/routes/{feature}.routes.ts`

```typescript
import { Router } from 'express'
import { authenticate } from '../middleware/authenticate'
import { {Feature}Service } from '../services/{feature}.service'
import { z } from 'zod'

const router = Router()

const CreateSchema = z.object({ ... })

router.post('/', authenticate, async (req, res, next) => {
  try {
    const body = CreateSchema.parse(req.body)
    const data = await {Feature}Service.create(req.user.id, body)
    res.status(201).json({ data, error: null })
  } catch (err) {
    next(err)
  }
})

export default router
```

## Step 2 — Create the service file
Location: `apps/api/src/services/{feature}.service.ts`

```typescript
import { db } from '../lib/db'
import { AppError } from '../lib/errors'

export const {Feature}Service = {
  async create(userId: string, data: CreateInput) {
    // business logic here
    return db.{model}.create({ data: { userId, ...data } })
  }
}
```

## Step 3 — Register the route
In `apps/api/src/app.ts`:
```typescript
import {feature}Routes from './routes/{feature}.routes'
app.use('/api/{feature}', {feature}Routes)
```

## Step 4 — Write a test
Location: `apps/api/src/__tests__/{feature}.integration.test.ts`
Test: happy path POST, validation error 400, auth error 401

## Rules to Follow
- Read docs/rules/api-design.md before implementing
- Read docs/rules/auth.md if route needs authentication
- All inputs validated with Zod
- Service handles all DB calls — no Prisma in routes
EOF

echo "✓ docs/skills/api-route.md created"

# ── docs/skills/react-page.md ────────────────────────────────────────────────
cat > docs/skills/react-page.md << 'EOF'
# Skill: How to Create a New Next.js Page

## Step 1 — Create the page file
Location: `apps/web/app/{route}/page.tsx`

```typescript
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import { authOptions } from '@/lib/auth'

export default async function {PageName}Page() {
  const session = await getServerSession(authOptions)
  if (!session) redirect('/login')

  return (
    <div>
      {/* page content */}
    </div>
  )
}
```

## Step 2 — Add loading state
Location: `apps/web/app/{route}/loading.tsx`
```typescript
export default function Loading() {
  return <div>Loading...</div>  // replace with skeleton
}
```

## Step 3 — Client components
If page needs interactivity, create a client component:
Location: `apps/web/components/{feature}/{ComponentName}.tsx`
```typescript
'use client'
import { useState } from 'react'
// ...
```

## Step 4 — Data fetching
- Server components: fetch directly with credentials
- Client components: use React Query hooks from `hooks/use{Feature}.ts`

## Rules
- Pages are server components by default — only add 'use client' when needed
- Auth check at the top of every protected page
- Loading states required for all async pages
- Use shadcn/ui components — never raw HTML for UI elements
EOF

echo "✓ docs/skills/react-page.md created"

# ── docs/skills/prisma-migration.md ──────────────────────────────────────────
cat > docs/skills/prisma-migration.md << 'EOF'
# Skill: How to Create a Prisma Migration

## Adding a new table or column

1. Edit `apps/api/prisma/schema.prisma`
2. Run: `pnpm --filter api prisma migrate dev --name describe_your_change`
   Example: `--name add_question_banks_table`
3. Verify migration file created in `apps/api/prisma/migrations/`
4. Run: `pnpm --filter api prisma generate` to update the client

## Migration naming convention
- snake_case, descriptive, present tense
- Good: `add_sessions_table`, `add_role_to_users`, `create_question_banks`
- Bad: `migration1`, `fix`, `update`

## NEVER
- Never edit an existing migration file
- Never delete a migration file
- Never run `prisma migrate reset` in production

## Rollback (dev only)
`pnpm --filter api prisma migrate reset` — resets dev DB and reruns all migrations

## Production deployment
Migrations run automatically in CI/CD before app deploy:
`pnpm --filter api prisma migrate deploy`
EOF

echo "✓ docs/skills/prisma-migration.md created"

# ── docs/skills/ai-feature.md ────────────────────────────────────────────────
cat > docs/skills/ai-feature.md << 'EOF'
# Skill: How to Add a New Claude-Powered Feature

## Step 1 — Write the prompt
Location: `docs/prompts/v1/{feature-name}.md`
Include: purpose, system prompt, user template with {{vars}}, output schema (Zod)

## Step 2 — Add the service method
Location: `apps/api/src/services/{feature}.service.ts`

```typescript
import { claude } from '../lib/claude'
import { z } from 'zod'

const OutputSchema = z.object({ ... })

export async function generateFeature(userId: string, input: FeatureInput) {
  const result = await claude.complete({
    promptKey: 'feature-name',
    version: 'v1',
    vars: { input }
  })
  return OutputSchema.parse(result)
}
```

## Step 3 — Decide: sync or async?
- Fast (<5s, user waits): call service directly in route, return result
- Slow (>5s, scoring/generation): queue a BullMQ job, return jobId, client polls status

## Step 4 — For async jobs
Create worker: `apps/api/src/workers/{feature}.worker.ts`
Queue name: `{feature}-queue`
Poll endpoint: `GET /api/{resource}/:id/status`

## Step 5 — Add cost logging
Every Claude call must log: user_id, prompt_key, input_tokens, output_tokens, created_at
Table: `ai_usage_logs`

## Rules
- Read docs/rules/ai-calls.md before implementing
- Never call Anthropic SDK directly — use lib/claude.ts
- Always validate Claude output with Zod
- Always handle Claude API errors gracefully (503 to client)
EOF

echo "✓ docs/skills/ai-feature.md created"

# ── apps/web placeholder ──────────────────────────────────────────────────────
cat > apps/web/.gitkeep << 'EOF'
# Next.js 14 frontend — scaffold in Phase 0
EOF

cat > apps/api/.gitkeep << 'EOF'
# Express API — scaffold in Phase 0
EOF

cat > packages/shared/.gitkeep << 'EOF'
# Shared TypeScript types — scaffold in Phase 0
EOF

echo "✓ App placeholders created"

# ── README.md ─────────────────────────────────────────────────────────────────
cat > README.md << 'EOF'
# InterviewAI

AI-powered mock interview preparation and simulation platform.

## What it does
- Paste a JD + Resume → get a personalised Q&A bank generated by Claude
- Study the bank with spaced repetition flashcards
- Take a proctored mock interview (camera + mic + live transcription)
- Get a scored debrief with per-answer feedback and improvement coaching

## Tech Stack
Next.js 14 · Express · PostgreSQL · Prisma · BullMQ · Claude API · Tailwind · shadcn/ui

## Project Structure
```
apps/web/          Next.js frontend
apps/api/          Express backend
packages/shared/   Shared TypeScript types
docs/              Planning, specs, rules, prompts, skills
```

## Getting Started
See CLAUDE.md for full setup instructions.

## Status
Phase 0 — Project scaffold in progress.
EOF

echo "✓ README.md created"

# ── Final summary ─────────────────────────────────────────────────────────────
echo ""
echo "✅ InterviewAI project structure created successfully!"
echo ""
echo "Files created:"
find . -type f | grep -v ".git" | sort
echo ""
echo "Next steps:"
echo "  1. cd ~/Documents/homespace/interviewai"
echo "  2. git add ."
echo '  3. git commit -m "initial: project plan, CLAUDE.md, docs structure"'
echo "  4. git push -u origin main"
echo ""
echo "Then come back and we will scaffold the actual app code 🚀"
EOF